version: "3.9"
    
services:
  cognito:
    image: jagregory/cognito-local:latest
    volumes:
      - .cognito:/app/.cognito
    ports:
      - "9229:9229"
    restart: always
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0