version: "3.9"
    
services:
  cognito:
    image: jagregory/cognito-local:latest
    volumes:
      - .cognito:/app/.cognito
    ports:
      - "9229:9229"
    restart: always
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "./localstack/s3:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=dashboard_user
      - MYSQL_DATABASE=dashboard_db
volumes:
  db:
    driver: local
